# Generated by Django 6.1.1 on 2026-09-28 17:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('query_hash', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('display_name', models.CharField(blank=True, max_length=512)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'query_hash'), name='unique_geocode_provider_query')],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identity_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('source_opis_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=8)),
                ('rack_id', models.CharField(max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geocode_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('geocode_provider', models.CharField(blank=True, max_length=64)),
                ('geocode_query', models.CharField(blank=True, max_length=512)),
                ('geocode_display_name', models.CharField(blank=True, max_length=512)),
                ('geocode_error', models.TextField(blank=True)),
                ('geocoded_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'city', 'name', 'station_id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='station_retail_price_positive'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='station_coordinates_together')],
            },
        ),
        migrations.CreateModel(
            name='FuelPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_hash', models.CharField(max_length=64, unique=True)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_row_number', models.PositiveIntegerField()),
                ('source_opis_id', models.CharField(max_length=32)),
                ('source_name', models.CharField(max_length=255)),
                ('source_address', models.CharField(max_length=255)),
                ('source_city', models.CharField(max_length=128)),
                ('source_state', models.CharField(max_length=8)),
                ('rack_id', models.CharField(max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=10)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_observations', to='stations.station')),
            ],
            options={
                'ordering': ['source_file_name', 'source_row_number'],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='observation_retail_price_positive')],
            },
        ),
        migrations.CreateModel(
            name='StationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(max_length=255)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='stations.station')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('station', 'normalized_name'), name='unique_station_alias_name')],
            },
        ),
    ]
