# Generated by Django 6.1.1 on 2026-09-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='station',
            index=models.Index(fields=['geocode_status', 'latitude', 'longitude'], name='station_geo_candidate_idx'),
        ),
    ]
